/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.managerstudent.ManagentOFStudent;

import com.mycompany.managerstudent.Student;
import com.mycompany.managerstudent.model.StudentList;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranbaonguyen
 */
public class ManageStudent extends javax.swing.JFrame {
    private StudentList studentList = new StudentList();
    private DefaultTableModel tableModel = null;

    /**
     * Creates new form ManageStudent
     */
    public ManageStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        inputFemale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        inputIdStudent = new javax.swing.JTextField();
        inputMale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputBirthday = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputAddress = new javax.swing.JTextArea();
        inputPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        inputImage = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Id Student");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 155, 81, 21);

        buttonGroup1.add(inputFemale);
        inputFemale.setText("Female");
        getContentPane().add(inputFemale);
        inputFemale.setBounds(230, 320, 76, 23);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("Manage Student");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(207, 39, 253, 43);
        getContentPane().add(inputIdStudent);
        inputIdStudent.setBounds(135, 153, 203, 26);

        buttonGroup1.add(inputMale);
        inputMale.setSelected(true);
        inputMale.setText("Male");
        getContentPane().add(inputMale);
        inputMale.setBounds(140, 320, 61, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Birthday");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 199, 63, 21);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(25, 362, 59, 21);
        getContentPane().add(inputBirthday);
        inputBirthday.setBounds(135, 197, 203, 26);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(25, 243, 43, 21);

        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        getContentPane().add(inputEmail);
        inputEmail.setBounds(135, 241, 203, 26);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Phonenumber");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(25, 283, 100, 21);

        inputAddress.setColumns(20);
        inputAddress.setRows(5);
        jScrollPane1.setViewportView(inputAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(137, 362, 253, 84);
        getContentPane().add(inputPhoneNumber);
        inputPhoneNumber.setBounds(137, 281, 203, 26);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Sex");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(25, 322, 27, 21);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Full name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(25, 111, 73, 21);
        getContentPane().add(inputName);
        inputName.setBounds(135, 109, 203, 26);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Phone number", "Sex", "Birthday", "Address"
            }
        ));
        jTable2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable2PropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(14, 452, 641, 165);

        jButton1.setText("Add");
        getContentPane().add(jButton1);
        jButton1.setBounds(422, 348, 75, 29);

        jButton2.setText("Delete");
        getContentPane().add(jButton2);
        jButton2.setBounds(515, 348, 84, 29);

        jButton4.setText("Update");
        getContentPane().add(jButton4);
        jButton4.setBounds(422, 395, 88, 29);

        jButton5.setText("Sort(code,name)");
        getContentPane().add(jButton5);
        jButton5.setBounds(522, 395, 145, 29);

        jButton6.setText("Search");
        getContentPane().add(jButton6);
        jButton6.setBounds(611, 348, 85, 29);

        inputImage.setText("jLabel8");
        inputImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputImageMouseClicked(evt);
            }
        });
        getContentPane().add(inputImage);
        inputImage.setBounds(450, 120, 140, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void jTable2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2PropertyChange

    private void inputImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputImageMouseClicked
        // TODO add your handling code here:
        JFileChooser jfc=new JFileChooser("/Users/tranbaonguyen/Desktop/ManagerStudent/src/main/java/Image");
        jfc.showOpenDialog(null);
        File file =jfc.getSelectedFile();
        Image img;
        try {
            img = ImageIO.read(file);
            inputImage.setText("");
            int width=inputImage.getWidth();
            int height=inputImage.getHeight();
            inputImage.setIcon(new ImageIcon(img.getScaledInstance(width,height,0)));
        } catch (IOException e) {
            System.out.println("Error: "+e.toString());
        }
    }//GEN-LAST:event_inputImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudent().setVisible(true);
            }
        });
    }
    
    public void initData() {
        studentList.addStudent(new Student("nguuen","gcd201888","07/12/2002",
                "nguyentb@gmail.com",395909420,"male","K48/11 truong son"));

        studentList.pushToTable(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextArea inputAddress;
    private javax.swing.JTextField inputBirthday;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JRadioButton inputFemale;
    private javax.swing.JTextField inputIdStudent;
    private javax.swing.JLabel inputImage;
    private javax.swing.JRadioButton inputMale;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPhoneNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
